yiisoft/html

README.md, composer.json, src/Html.php, tests/HtmlTest.php, tests/HtmlTestModel.php, tests/TestCase.php
=> Cleanup proposal (#1)

src/Html.php
=> Remove final class extend from yii-bootstrap4.

src/Html.php
=> Fix function addCssClass typehint (string|null): ?string.

src/Html.php, tests/HtmlTest.php
[x] add typehints property, fixed phpdocs, correction minors.
=> Add typehints, fix phpdocs.

src/Html.php
=> Remove cast string value.

src/Html.php
=> Fix phpdocs

src/Html.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Fix constants

src/Html.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Fix constant visibility

composer.json, src/Html.php
- Minor refactoring for arrayable names.
- Remove dependency on yiisoft/strings.
=> Minor refactoring and remove dependency on yiisoft/strings.

README.md
=> Fix mutation testing badge.

composer.json
=> Update infection and psalm

.github/workflows/bc.yml_, .github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, README.md, composer.json
=> Update dev dependencies, pipelines and README.md.

README.md, composer.json, src/Html.php
=> Adopt psalm + Improve readme + Update dev dependencies

src/Html.php, tests/HtmlTest.php
| Fixed issues  | https://github.com/yiisoft/html/issues/42
=> Encode tag content by default

src/Html.php
=> Improve psalm annotations for Html::addCssClass

src/Html.php
=> Fix: <script> content should not be encoded

README.md
=> Add new feature with variadic arguments in "content" to readme.

CHANGELOG.md, src/Tag/Script.php, src/Tag/Style.php, tests/common/Tag/ScriptTest.php, tests/common/Tag/StyleTest.php
This is need for https://github.com/yiisoft/view/pull/138 (see https://github.com/yiisoft/view/blob/25421e1285d13fa965d39fd38f13a38a5cd8dda6/src/WebView.php#L636)
=> Add methods Script::getContent() and Style::getContent()

CHANGELOG.md, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
=> Add support individual attributes for inputs in `CheckboxList` and `RadioList` widgets

CHANGELOG.md, README.md
=> Cleanup + fix order in changelog

CHANGELOG.md, README.md, src/Html.php, src/Tag/H1.php, src/Tag/H2.php, src/Tag/H3.php, src/Tag/H4.php, src/Tag/H5.php, src/Tag/H6.php, tests/common/HtmlTest.php, tests/common/Tag/H1Test.php, tests/common/Tag/H2Test.php, tests/common/Tag/H3Test.php, tests/common/Tag/H4Test.php, tests/common/Tag/H5Test.php, tests/common/Tag/H6Test.php
=> Add classes for heading tags H1-6

CHANGELOG.md, README.md, src/Html.php, src/Tag/Title.php, tests/common/HtmlTest.php, tests/common/Tag/TitleTest.php
=> Add class for tag `Title` and method `Html::title()`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Base/NormalTag.php, src/Tag/Form.php, tests/common/HtmlTest.php, tests/common/Tag/FormTest.php
=> Add class for tag `Form` and method `Html::form()`

CHANGELOG.md, src/Html.php
=> Remove psalm type HtmlAttributes

CHANGELOG.md, src/Tag/Optgroup.php, src/Tag/Select.php, tests/common/Tag/SelectTest.php
=> Add individual attributes of options and option groups support to method `Select::optionsData()`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Datalist.php, src/Tag/Input.php, src/Tag/Input/Range.php, tests/common/HtmlTest.php, tests/common/Tag/DatalistTest.php, tests/common/Tag/Input/RangeTest.php, tests/common/Tag/InputTest.php
=> Add class for tag `Datalist` and for input with type `Range`

CHANGELOG.md, README.md, src/Tag/Base/Tag.php, src/Widget/ButtonGroup.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/common/Tag/Base/TagTest.php, tests/common/Widget/ButtonGroupTest.php
=> Add widget `ButtonGroup` and method `Tag::unionAttributes()`

CHANGELOG.md, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
=> Add methods `CheckboxList::name()` and `RadioList::name()`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Fieldset.php, src/Tag/Legend.php, tests/common/HtmlTest.php, tests/common/Tag/FieldsetTest.php, tests/common/Tag/LegendTest.php
=> Add class for tag `Legend`, class for tag `Fieldset`, methods `Html::legend()` and `Html::fieldset()`

CHANGELOG.md, src/Tag/Input/File.php, tests/common/Tag/Input/FileTest.php
=> Add `File::uncheckInputTagAttributes()`

.github/workflows/build.yml, .github/workflows/dependency.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, .scrutinizer.yml
=> Update dependencies workflows.

CHANGELOG.md, README.md, src/Tag/Base/Tag.php, tests/common/Tag/BTest.php, tests/common/Tag/Base/TagTest.php, tests/common/Tag/ColgroupTest.php, tests/common/Tag/DivTest.php, tests/common/Tag/EmTest.php, tests/common/Tag/H1Test.php, tests/common/Tag/H2Test.php, tests/common/Tag/H3Test.php, tests/common/Tag/H4Test.php, tests/common/Tag/H5Test.php, tests/common/Tag/H6Test.php, tests/common/Tag/ITest.php, tests/common/Tag/LiTest.php, tests/common/Tag/PTest.php, tests/common/Tag/SpanTest.php, tests/common/Tag/StrongTest.php, tests/common/Tag/TableTest.php, tests/common/Tag/TbodyTest.php, tests/common/Tag/TfootTest.php, tests/common/Tag/TheadTest.php, tests/common/Tag/TrTest.php, tests/common/Widget/ButtonGroupTest.php
=> Add `Tag::addClass()` and deprecate `Tag::class()`

CHANGELOG.md, composer.json
=> Raise `yiisoft/arrays` version to `^2.0`

CHANGELOG.md, src/Tag/Img.php, tests/common/Tag/ImgTest.php
=> Add `loading()` method to `Img` tag

CHANGELOG.md, src/Html.php, src/Tag/Input.php, tests/common/HtmlTest.php, tests/common/Tag/InputTest.php
=> Remove `Html::fileInput()` and `Input::file()`. Rename `Input::fileControl()` to `Input::file()`

CHANGELOG.md, src/NoEncode.php, src/NoEncodeStringableInterface.php, src/Tag/Base/Tag.php, src/Widget/ButtonGroup.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php
=> `NoEncodeStringableInterface` extend `Stringable` interface

src/Tag/Select.php, tests/common/Objects/TestTagContentTrait.php, tests/common/Tag/Base/TagContentTraitTest.php
=> Kill last mutant

README.md
=> Add psalm level badge

.styleci.yml, CHANGELOG.md, README.md, src/Html.php, src/Tag/Small.php, tests/common/HtmlTest.php, tests/common/Tag/SmallTest.php
=> Add small tag

CHANGELOG.md, src/Html.php, tests/common/HtmlTest.php
=> Add attributes to Html::ul and Html::ol (#174)

CHANGELOG.md, README.md, src/Html.php, src/Tag/Html.php, tests/common/HtmlTest.php, tests/common/Tag/HtmlTest.php
=> Add html tag

CHANGELOG.md, src/Widget/CheckboxList/CheckboxItem.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioItem.php, src/Widget/RadioList/RadioList.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
=> Add ability set attributes for label of items in widgets `CheckboxList` and `RadioList`

src/Html.php, src/Tag/CustomTag.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/html/issues/189
=> update src folder links

CHANGELOG.md, README.md, src/Html.php, src/Tag/Hr.php, tests/common/HtmlTest.php, tests/common/Tag/HrTest.php
| Fixed issues | #191 
Test cases Passed
=> Add class for <hr> tag #191

README.md
=> Remove Scrutinizer badge from README

CHANGELOG.md, composer-require-checker.json, composer.json, phpunit.xml.dist, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/php81/Support/IntegerEnum.php, tests/php81/Support/StringEnum.php, tests/php81/Widget/CheckboxList/CheckboxListTest.php, tests/php81/Widget/RadioList/RadioLIstTest.php
=> Add backed enums value support to `CheckboxList` and `RadioList`

CHANGELOG.md, src/Tag/Script.php, tests/common/Tag/ScriptTest.php
=> Add nonce attribute to script tag

.github/workflows/bc.yml, CHANGELOG.md, rector.php, src/Tag/Select.php, tests/php81/Tag/SelectTest.php
=> Add backed enumeration value support to `Select` tag

CHANGELOG.md, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/Widget/CheckboxListTest.php, tests/Widget/RadioListTest.php
=> Add ability to wrap items in checkbox and radio lists

CHANGELOG.md, src/Html.php
=> Fix #232: Render loading attribute before src

CHANGELOG.md, composer.json, psalm.xml
=> Fix psalm + Improve PHP constraint

CHANGELOG.md, src/Tag/Link.php
=> Explicitly marking parameters as nullable

CHANGELOG.md, src/Html.php, src/Tag/Base/Tag.php, tests/Tag/Base/TagTest.php
=> Add `Tag::addStyle()` and `Tag::removeStyle()` methods
