src/Html.php
Fix minor corrections:
Changes are necessary for yii-form.
=> Fix minor corrections.

src/Html.php, tests/HtmlTest.php
Allow set `aria-` attriubtes ([info](https://www.w3.org/TR/wai-aria-1.1/#state_prop_def)) as array. For example:
```php
Html::tag('div', '', ['aria' => ['a' => 1, 'b' => 'c']])); // <div aria-a="1" aria-b="c"></div>
```
=> Add "aria" to data attributes.

src/Html.php, tests/HtmlTest.php
Add option `wrapInput` for checkbox and radio.
`wrapInput` use when has label.
if `wrapInput` is true result will be `<label><input> Label</label>`,  else `<input> <label>Label</label>`.
+ more tests for `Html::generateId()`
=> Add option "wrapInput" for checkbox and radio + tests

README.md, src/Html.php, tests/HtmlTest.php
| Fixed issues  | #23 
- Remove `Html::escapeJsRegularExpression`
- Add `Html::normalizeRegexpPattern`
=> Remove Html::escapeJsRegularExpression and add Html::normalizeRegexpPattern

README.md, src/Html.php, tests/EncodeTest.php, tests/HtmlTest.php
| Fixed issues  | #26
Added methods:
- `encodeAttribute`
- `encodeQuotedAttribute`
- `escapeJsStringValue`
Modify methods:
- `encode`
Removed methods:
- `decode`
=> Add encode methods for different contexts

README.md, src/Html.php, tests/HtmlTest.php
Added methods for generate often used tags: `div`, `span` and `p`.
=> Add Html::div(), Html::span() and Html::p().

composer.json, src/Html.php, tests/HtmlTest.php
| Fixed issues  | #44 
Seems equal bug has in yii2...
=> Fix error in Html::renderSelectOptions when use "encode" as key in items array.

composer.json, psalm.xml, src/Html.php, tests/HtmlTest.php, tests/Objects/ArrayAccessObject.php, tests/Objects/IterableObject.php
| Is bugfix?    |  ❌
- In Html::renderSelectOptions() pass 3 argument not by reference
- Fix: incorrect work with iterable $selection in methods checkboxList, radioList and renderSelectOptions
- Update dev dependencies
- Adopt Psalm (error level 1)
- Clean up
=> In Html::renderSelectOptions() pass 3 argument not by reference  + Adopt psalm.

src/Tag/Base/ListTag.php, tests/Tag/Base/ListTagTest.php
For example:
```php
echo Html::ul()->strings(['A', 'B'], ['class' => 'red']);
```
Result will be:
```html
<ul>
<li class="red">A</li>
<li class="red">B</li>
</li>
```
=> Add parameter $attributes to ListTag::strings()

README.md, src/Html.php, src/NoEncodeStringableInterface.php, src/Tag/Base/BooleanInputTag.php, src/Tag/Base/ContentTag.php, src/Tag/Base/NotEncodeStringableInterface.php, src/Tag/Base/Tag.php, src/Tag/CustomTag.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/HtmlTest.php, tests/Objects/StringableObject.php, tests/Tag/Base/ContentTagTest.php, tests/Tag/CustomTagTest.php, tests/Widget/CheckboxListTest.php, tests/Widget/RadioListTest.php
Implementaion of ideas from https://github.com/yiisoft/html/issues/49#issuecomment-753452870
- Add `NotEncodeStringableInterface`. Objects implemnted this interface will not be encoded by default in tag contents.
- `ContentTag::content()` and `CustomTag::content()` use variadic `$content` argument.
- Add method `__toString()` to `CheckboxList` and `RadioList`.
- Remove `ContentTag::encodeSpaces()` and `CustomTag::encodeSpaces()`.
- `ContentTag` and `CustomTag` use default encode as `null`. In this mode encode all, exclude stringable object implemented `NotEncodeStringableInterface`.
Example:
```php
$items = [
'Hello > ',
Span::tag()->content('World')
];
echo …
```
=> Add NotEncodeStringableInterface and allow accept array in ContentTag::content()

.github/workflows/dependency.yml, composer.json, dependency-checker.json
=> Add dependency checker

CHANGELOG.md, README.md, src/Html.php, src/Tag/Br.php, tests/common/HtmlTest.php, tests/common/Tag/BrTest.php
This is popular tag and it is convenient to use in mixed content. For example:
```php
echo Html::p()->content(
'Hello',
Html::br(),
'World',
);
```
=> Add tag BR

CHANGELOG.md, README.md, psalm.xml, src/Html.php, src/Tag/B.php, src/Tag/Em.php, src/Tag/I.php, src/Tag/Strong.php, tests/common/HtmlTest.php, tests/common/Tag/BTest.php, tests/common/Tag/EmTest.php, tests/common/Tag/ITest.php, tests/common/Tag/StrongTest.php
Add popular tags that convenient to use via `Html::b()`, `Html::em()`, etc.
=> Add tags `Em`, `Strong`, `B` and `I`

CHANGELOG.md, src/Tag/Link.php, tests/common/Tag/LinkTest.php
=> Add methods `as()` and `preload()` to the `Link` tag

CHANGELOG.md, composer.json, src/Html.php, src/Tag/Base/BooleanInputTag.php, src/Tag/Base/Tag.php, tests/common/Tag/Base/BooleanInputTagTest.php, tests/common/Tag/Base/TagTest.php
Also update dev dependencies and fix psalm errors
=> Allow pass `null` argument to methods `Tag::class()`, `Tag::replaceClass()`, `BooleanInputTag::label()` and   `BooleanInputTag::sideLabel()`

CHANGELOG.md, README.md, src/NoEncode.php, tests/common/NoEncodeTest.php
| Fixed issues  | #76
Psalm errors fixed in #80 
May be rename `NoEncode` to `AsIs`? Will be `AsIs::string('<i>hello</i>')`.
=> Add `NoEncode` class designed to use as non-encoded content in HTML tags

CHANGELOG.md, composer.json, src/Html.php, src/Tag/Base/ListTag.php, src/Tag/Base/TableRowsContainerTag.php, src/Tag/Base/Tag.php, src/Tag/Colgroup.php, src/Tag/Tr.php, tests/common/HtmlTest.php, tests/common/Tag/Base/InputTagTest.php, tests/common/Tag/Base/TagTest.php, tests/common/Tag/LinkTest.php, tests/common/Tag/MetaTest.php, tests/common/Tag/SelectTest.php, tests/common/Tag/TextareaTest.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
=> For attributes with empty string value generated only attribute name without value and character `=`

CHANGELOG.md, src/Html.php
Order correct:
```HTML
<input type="email" id="attributesvalidatorform-email" name="AttributesValidatorForm[email]" value="" maxlength="20" minlength="8" required>
```
Current Order: 
```HTML
<input type="email" id="attributesvalidatorform-email" name="AttributesValidatorForm[email]" value="" maxlength="20" required minlength="8">
```
The `minlength` attribute must be added since the validator `HasLength::class` adds it, it is also common to use it with `maxlength`.
=> Fix order attributes.

CHANGELOG.md, src/Tag/Select.php, tests/common/Support/AssertTrait.php, tests/common/Tag/SelectTest.php
=> Add option groups support to method `Select::optionsData()`

CHANGELOG.md, src/Html.php, tests/common/HtmlTest.php
=> Add `$attributes` to `Html` methods `input()`, `buttonInput()`, `submitInput()` and `resetInput()`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Input.php, src/Tag/Input/File.php, tests/common/HtmlTest.php, tests/common/Tag/Input/FileTest.php, tests/common/Tag/InputTest.php
=> Add specialized class `File` for an input tag with type `file`

src/Tag/Input/File.php, src/Tag/Input/Range.php, tests/common/Tag/Input/FileTest.php, tests/common/Tag/Input/RangeTest.php
Rename methods:
- `File::uncheckInputTagAttributes()` → `File::uncheckInputAttributes()`
- `Range::outputTagAttributes()` → `Range::outputAttributes()`
- `Range::outputTagName()` → `Range::outputTag()`
New methods:
- `File::replaceUncheckInputAttributes()`
- `Range::replaceOutputAttributes()`
=> Refactoring for more consistency

tests/common/Tag/ArticleTest.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
----
Found some more.
=> Separate chain calls

CHANGELOG.md, src/Tag/Form.php, tests/common/Tag/FormTest.php
=> Add shortcut methods for enctype in `Form`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Base/ListTag.php, src/Tag/Base/Tag.php, src/Tag/Input/File.php, src/Tag/Input/Range.php, src/Tag/Optgroup.php, src/Tag/Select.php, src/Tag/Tr.php, src/Widget/ButtonGroup.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/common/Tag/ArticleTest.php, tests/common/Tag/Base/TagTest.php, tests/common/Tag/BodyTest.php, tests/common/Tag/FieldsetTest.php, tests/common/Tag/Input/FileTest.php, tests/common/Tag/Input/RangeTest.php, tests/common/Widget/ButtonGroupTest.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
=> Add `addAttributes()` and deprecate `attributes()`

CHANGELOG.md, src/Tag/Base/Tag.php, tests/common/Tag/BTest.php, tests/common/Tag/Base/TagTest.php, tests/common/Tag/ColgroupTest.php, tests/common/Tag/DivTest.php, tests/common/Tag/EmTest.php, tests/common/Tag/H1Test.php, tests/common/Tag/H2Test.php, tests/common/Tag/H3Test.php, tests/common/Tag/H4Test.php, tests/common/Tag/H5Test.php, tests/common/Tag/H6Test.php, tests/common/Tag/ITest.php, tests/common/Tag/LiTest.php, tests/common/Tag/PTest.php, tests/common/Tag/SpanTest.php, tests/common/Tag/StrongTest.php, tests/common/Tag/TableTest.php, tests/common/Tag/TbodyTest.php, tests/common/Tag/TfootTest.php, tests/common/Tag/TheadTest.php, tests/common/Tag/TrTest.php, tests/common/Widget/ButtonGroupTest.php
=> Remove `Tag::class()` and rename `Tag::replaceClass()` to `Tag::class()`

CHANGELOG.md, README.md, src/Html.php, src/Tag/Base/ListTag.php, src/Tag/Base/Tag.php, src/Tag/Input/File.php, src/Tag/Input/Range.php, src/Tag/Optgroup.php, src/Tag/Select.php, src/Tag/Tr.php, src/Widget/ButtonGroup.php, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/common/Tag/Base/TagTest.php, tests/common/Tag/BodyTest.php, tests/common/Tag/FieldsetTest.php, tests/common/Tag/Input/FileTest.php, tests/common/Tag/Input/RangeTest.php, tests/common/Widget/ButtonGroupTest.php, tests/common/Widget/CheckboxListTest.php, tests/common/Widget/RadioListTest.php
| Fixed issues  | #125 
- `Range`: remove `outputAttributes()`, rename `replaceOutputAttributes()` to `outputAttributes()`
- `File`: remove `uncheckInputAttributes()`, rename `replaceUncheckInputAttributes()` to `uncheckInputAttributes()`
- `CheckboxList`: remove `individualInputAttributes()`, rename `replaceIndividualInputAttributes()` to `individualInputAttributes()`
- `CheckboxList`: remove `checkboxAttributes()`, rename `replaceCheckboxAttributes()` to `checkboxAttributes()`
- `RadioList`: remove `individualInputAttributes()`, rename `replaceIndividualInputAttributes()` to `individualInputAttributes()`
- `RadioList`: remove `radioAttributes()`, rename `replaceRadioAttributes()` to …
=> Remove methods `*attributes()` and rename `replace*Attributes()` to `*attributes()`

.github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml, .github/workflows/rector.yml, .github/workflows/static.yml, CHANGELOG.md, src/Html.php, tests/common/HtmlTest.php
=> Fix loss keys of named class in `Html::addCssClass()` when class in passed options is string

CHANGELOG.md, src/Html.php, tests/common/HtmlTest.php
=> Allow pass `null` as class to `Html::addCssClass()`

CHANGELOG.md, src/Tag/Form.php, tests/common/Tag/FormTest.php
=> Replace constant `PHP_EOL` to `"\n"`

CHANGELOG.md, src/Html.php, src/Tag/Textarea.php, tests/common/Tag/TextareaTest.php
=> Add `Stringable` and array values support to textarea tag

CHANGELOG.md, src/Tag/Base/BooleanInputTag.php, tests/Tag/Base/BooleanInputTagTest.php
=> Add optional `wrap` parameter to `BooleanInputTag::label()`

CHANGELOG.md, src/Widget/CheckboxList/CheckboxList.php, src/Widget/RadioList/RadioList.php, tests/Widget/CheckboxListTest.php, tests/Widget/RadioListTest.php
=> Add checkbox/radio lists methods to set wrap classes

.github/workflows/bc.yml, CHANGELOG.md, src/Html.php, src/Tag/Base/Tag.php, tests/HtmlTest.php, tests/Support/ClassEnum.php, tests/Tag/Base/TagTest.php
=> Enhance `addClass()` and `class()` methods to support `BackedEnum` for CSS classes.

CHANGELOG.md, src/Tag/Button.php, tests/Tag/ButtonTest.php
| New feature?  | ✔️/
| Fixed issues  | Fix #223
=> Fix #223: Make `$content` optional in `Button` factories

CHANGELOG.md, composer.json, src/Tag/Select.php, tests/Tag/SelectTest.php
=> Allow to pass `null` to `Select::value()` method

CHANGELOG.md, README.md, src/Html.php, src/Tag/Input.php, src/Tag/Input/Color.php, tests/HtmlTest.php, tests/Tag/Input/ColorTest.php, tests/Tag/InputTest.php
=> Add `Html::colorInput()` and `Input::color()`
